export const POST_REGISTER_REQUEST="POST_REGISTER_REQUEST";
export const POST_REGISTER_SUCCESS=" POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILURE="POST_REGISTER_FAILURE";

export const POST_LOGIN_REQUEST="POST_LOGIN_REQUEST";
export const POST_LOGIN_SUCCESS=" POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILURE="POST_LOGIN_FAILURE";

// FOR getting all pokemon.
export const GETALLPOKEMON_REQUEST="GETALLPOKEMON_REQUEST";
export const GETALLPOKEMON_SUCCESS=" GETALLPOKEMON_SUCCESS";
export const GETALLPOKEMON_FAILURE="GETALLPOKEMON_FAILURE";

// USER SPECFIC POKEMON OR GETING USER BY ID SO THAT ITS ADOPTED POKEMON AN BE SEEN
export const GETUSERPOKEMON_REQUEST="GETUSERPOKEMON_REQUEST";
export const GETUSERPOKEMON_SUCCESS="GETUSERPOKEMON_SUCCESS";
export const GETUSERPOKEMON_FAILURE="GETUSERPOKEMON_FAILURE";







